name: Run PR
run-name: Run PR by ${{github.actor}}
on:
  pull_request:
    types: [opened,reopened,edited,synchronize]
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci
      - name: Run basic jest tests
        run: npm run test:jest

  Create-Android-Build:

    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci     
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Prepare to build
        run: npm run prebuild:clean:silent

      - name: Build Android release
        run: npm run android:release


  Create-iOS-Build:
    runs-on: macos-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci


      - name: Prepare 
        run: npm run prebuild:clean:silent
 #     - name: Prepare ios build
 #       run: npm run ios
  

#  Test-Android-Build:
#      runs-on: self-hosted
#      steps:
#      
#      - name: Install app in simulator
#        run: npm run emu:install:ReleaseApp
#      - name: Run Maestro
#        run: npm run test:maestro

