name: Run PR
run-name: Run PR by ${{github.actor}}
on:
  pull_request:
    types: [opened,reopened,edited,synchronize]
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci
      - name: Run basic jest tests
        run: npm run test:jest

  Create-Android-Build:

    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci     
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Prepare to build
        run: npm run prebuild:clean:silent

      - name: Build Android release
        run: npm run android:release

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.G_ACCOUNT_SECRET }}
          filename: "./android/app/build/outputs/apk/release/app-release.apk"
          folderId: ${{ secrets.G_FOLDER_ID }}
          name: "app-release.apk" # optional string
          overwrite: "true" # optional boolean


  Create-iOS-Build:
    runs-on: macos-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - name: Install node modules
        run: npm ci
      - name: Prepare 
        run: npm run prebuild:clean:silent
      - name: Prepare ios build
        run: npm run ios:build
  

  Test-Android-Build:
    runs-on: self-hosted
    needs: Create-Android-Build
    steps:
      - name: Download file APK
        uses: k0staa/download-gdrive-file-action@v1
        with:
          service-account-key-json: ${{ secrets.G_ACCOUNT_SECRET }}
          download-file-name: app-release.apk
          download-to: ./android/app/build/outputs/apk/release/
            
      - name: Install app in simulator
        run: npm run emu:install:ReleaseApp
      - name: Run Maestro
        run: npm run test:maestro

